sudo: required
services:
  - docker 


before_install: 
  - docker build -t saileshchandran/docker-react -f Dockerfile.dev .

script:
  #- docker run -e CI=true saileshchandran/docker-react npm run test
  - docker run saileshchandran/docker-react npm run test -- --coverage